# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestLoginout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginout(self):
    self.driver.get("https://www.bom2buy.com/")
    self.driver.set_window_size(1440, 693)
    self.driver.find_element(By.LINK_TEXT, "登录").click()
    self.driver.find_element(By.ID, "email-mobile").click()
    self.driver.find_element(By.ID, "email-mobile").send_keys("jiahui@eefocus.com")
    self.driver.find_element(By.ID, "password").send_keys("zjh11233")
    self.driver.find_element(By.CSS_SELECTOR, ".signin").click()
    self.driver.find_element(By.ID, "email-mobile").send_keys("jiahui@eefocus.com")
    self.driver.find_element(By.ID, "email-mobile").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "password").send_keys("zjh112233")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "password").send_keys("zjh112233")
    self.driver.find_element(By.LINK_TEXT, "退出").click()
  
