# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestUntitled():
   def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
 # def teardown_method(self, method):
    self.driver.quit()
  
 # def test_untitled(self):
    self.driver.get("https://enterprise.bom2buy.com/user/login")
    self.driver.set_window_size(1266, 695)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("candicezhangjiahui@126.com")
    self.driver.find_element(By.ID, "password").send_keys("zjh112233")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.LINK_TEXT, "BOM 列表")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "BOM 列表").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "user Test bom").click()
    self.driver.find_element(By.CSS_SELECTOR, ".antd-pro-pages-bom2buy-list-list-list-header-index-bomStatus").click()
    self.driver.find_element(By.CSS_SELECTOR, "#state .ant-select-selection__rendered").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-dropdown-menu-item-active").click()
    self.driver.find_element(By.ID, "comment").click()
    self.driver.find_element(By.ID, "comment").send_keys("测试bom状态\n")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn-primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn-primary")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-table-row:nth-child(3) > .antd-pro-pages-bom2buy-list-list-engineer-index-lifecycle").click()
    self.driver.close()
  
